platform :android do
    lane :test do
        puts("hi")
        # gradle(task: 'clean', project_dir: './android')
        # gradle(task: 'assemble', build_type: 'Release', project_dir: './android')
    end
end