platform :android do
    lane :test do |options|
        # puts( (options[:tag]))
        # gradle(task: 'clean', project_dir: './android')
        gradle(task: 'assemble', build_type: 'Release', project_dir: './android')
    end
end

platform :ios do
    lane :test do 
        build_ios_app(scheme:"Releasep", project_dir: './ios')
    end
end
