platform :android do
    lane :test do |options|
        puts("hello from android")
        # puts( (options[:tag]))
        # gradle(task: 'clean', project_dir: './android')
        # gradle(task: 'assemble', build_type: 'Release', project_dir: './android')
    end
end