name: CI/CD
on:
  push:
    branches:
      - main
  # release:
  #   types:
  #     - published
jobs:
  #   build-ios:
  #     runs-on: macos-latest
  #     if: contains(github.event.release.body, 'build_ios true')
  #     steps:
  #       - name: Checkout repo
  #         uses: actions/checkout@v2
  #       - name: Setup Node
  #         uses: actions/setup-node@v3
  #         with:
  #           node-version: 16
  #       - name: Setup Ruby
  #         uses: actions/setup-ruby@v1
  #         with:
  #           ruby-version: 2.7
  #       - name: Install bundle
  #         run: bundle install
  #       - name: Install packages
  #         run: npm install
  # - name: Save release description to file
  #   shell: bash
  #   run: |
  #     description="${{ github.event.release.body }}"
  #     # Print the description without the first 3 lines
  #     echo "${description}" | tail -n + 4 > ios/CHANGELOG.md
  #       - name: Build app
  #         run: cd ios && bundle exec fastlane ios test
  build-android:
    runs-on: ubuntu-latest
    # if: contains(github.event.release.body, 'build_android true')
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: adopt
      - name: Install bundle
        run: bundle install
      - name: Install packages
        run: npm install
      - name: Change gradlew permisssion
        run: chmod +rwx ./android/gradlew
      # - name: Save release description to file
      #   shell: bash
      #   run: |
      #     description="${{ github.event.release.body }}"
      #     # Print the description without the first 3 lines
      #     echo "${description}" | tail -n + 4 > android/CHANGELOG.md
      - name: Run Fastlane
        shell: bash
        run: cd android && bundle exec fastlane android test
