name: Fastlane
on:
  push:
    branches:
      - main
jobs:
  build-ios:
    runs-on: macos-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7
      - name: Install bundle
        run: bundle install
      - name: Install packages
        run: npm install
      - name: Install pods
        run: cd ios && pod install
      - name: Install bundle
        run: bundle install
      - name: Build app
        run: bundle exec fastlane ios test


  # build-android:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout repo
  #       uses: actions/checkout@v2
  #     - name: Setup Node
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: 16
  #     - name: Setup Ruby
  #       uses: actions/setup-ruby@v1
  #       with:
  #         ruby-version: 2.7
  #     - name: Setup Java
  #       uses: actions/setup-java@v2
  #       with:
  #         java-version: '17'
  #         distribution: adopt
  #     - name: Install bundle
  #       run: bundle install
  #     - name: Install packages
  #       run: npm install
  #     - name: Change gradlew permisssion
  #       run: chmod +rwx ./android/gradlew
  #     - name: Run Fastlane
  #       run: bundle exec fastlane android test tag:1.5.6