name: CI/CD 
on:
  release:
    types: 
      - published
jobs:
  build-ios:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Print release body
        run: |
          
          echo ${{ github.event.release.body | sed '1,2d'}}


# name: After Release

# on:
#   release:
#     types: 
#       - published

# jobs:
#   after-release:
#     runs-on: ubuntu-latest
#     # run if release description contains "build_android: true"
#     if: contains(github.event.release.body, 'build_android true')
#     steps:
#       - run: echo "Name ${{ github.event.release.name }} Description ${{ github.event.release.body }}"