name: Steps test
on:
  push:
    branches:
      - main
jobs:
  job-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        id: checkout
        uses: actions/checkout@v2
      - name: Test action 1
        id: test1
        run: echo action 1
      - name: Test action 2
        id: test2
        run: echo action 2